//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PointDBEntities : DbContext
    {
        public PointDBEntities()
            : base("name=PointDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Point> Points { get; set; }
        public virtual DbSet<PointFee> PointFees { get; set; }
        public virtual DbSet<PointPayment> PointPayments { get; set; }
        public virtual DbSet<StudentPoint> StudentPoints { get; set; }
    }
}
